[workspace]
resolver = "2"

members = [
    "modules/axalloc",
    "modules/axconfig",
    "modules/axdisplay",
    "modules/axdriver",
    "modules/axfs-ng",
    "modules/axhal",
    "modules/axinput",
    "modules/axlog",
    "modules/axmm",
    "modules/axdma",
    "modules/axnet",
    "modules/axruntime",
    "modules/axsync",
    "modules/axtask",

    "api/axfeat",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Yuekai Jia <equation618@gmail.com>"]
license = "GPL-3.0-or-later OR Apache-2.0 OR MulanPSL-2.0"
homepage = "https://github.com/arceos-org/arceos"
documentation = "https://arceos-org.github.io/arceos"
repository = "https://github.com/arceos-org/arceos"
keywords = ["arceos", "kernel"]
categories = ["os", "no-std"]

[workspace.dependencies]
axstd = { path = "ulib/axstd" }
axlibc = { path = "ulib/axlibc" }

arceos_api = { path = "api/arceos_api" }
arceos_posix_api = { path = "api/arceos_posix_api" }
axfeat = { path = "api/axfeat" }

axalloc = { path = "modules/axalloc" }
axconfig = { path = "modules/axconfig" }
axdisplay = { path = "modules/axdisplay" }
axdriver = { path = "modules/axdriver" }
axfs-ng = { path = "modules/axfs-ng" }
axhal = { path = "modules/axhal" }
axinput = { path = "modules/axinput" }
axlog = { path = "modules/axlog" }
axmm = { path = "modules/axmm" }
axnet = { path = "modules/axnet" }
axruntime = { path = "modules/axruntime" }
axsync = { path = "modules/axsync" }
axtask = { path = "modules/axtask" }
axdma = { path = "modules/axdma" }

allocator = { git = "https://github.com/Starry-Mix-THU/allocator.git", rev = "d5feebd" }
axbacktrace = "0.1"
axcpu = "0.2"
axerrno = { git = "https://github.com/Starry-Mix-THU/axerrno.git", rev = "f5d8f86" }
axfs-ng-vfs = { git = "https://github.com/Starry-Mix-THU/axfs-ng-vfs.git", rev = "60491ba" }
axio = { git = "https://github.com/Starry-Mix-THU/axio.git", rev = "4ececd3" }
axplat = "0.1"
bindgen = "0.72"
cfg-if = "1.0"
chrono = { version = "0.4", default-features = false }
crate_interface = "0.1.4"
enum_dispatch = "0.3.13"
futures = { version = "0.3.31", default-features = false, features = ["alloc"] }
hashbrown = "0.15.4"
kernel_guard = "0.1"
kspin = "0.1"
lazy_static = { version = "1.5", features = ["spin_no_std"] }
lazyinit = "0.2"
lock_api = { version = "0.4", default-features = false }
log = "=0.4.21"
memory_addr = "0.4"
memory_set = "0.4"
page_table_entry = "0.5"
page_table_multiarch = "0.5"
percpu = "0.2"
rand = "0.9"
scope-local = "0.1"
spin = "0.9"

[profile.release]
lto = true

[patch.crates-io]
axbacktrace = { git = "https://github.com/Starry-Mix-THU/axbacktrace.git", rev = "322f6da" }
axcpu = { path = "../module-local/axcpu" }
page_table_entry = { git = "https://github.com/starry-mix-rk3588/page_table_multiarch", rev = "3f697c8" }
page_table_multiarch = { git = "https://github.com/starry-mix-rk3588/page_table_multiarch", rev = "3f697c8" }
