[package]
name = "axhal"
version.workspace = true
edition.workspace = true
authors = ["Yuekai Jia <equation618@gmail.com>"]
description = "ArceOS hardware abstraction layer, provides unified APIs for platform-specific operations"
license.workspace = true
homepage.workspace = true
repository = "https://github.com/arceos-org/arceos/tree/main/modules/axhal"
documentation = "https://arceos-org.github.io/arceos/axhal/index.html"

[features]
smp = ["axplat-x86-pc?/smp", "axplat-aarch64-qemu-virt?/smp", "axplat-riscv64-qemu-virt?/smp", "axplat-loongarch64-qemu-virt?/smp", "axplat/smp"]
irq = ["linkme", "axplat-x86-pc?/irq", "axplat-aarch64-qemu-virt?/irq", "axplat-riscv64-qemu-virt?/irq", "axplat-loongarch64-qemu-virt?/irq", "axplat/irq"]
fp-simd = ["axcpu/fp-simd", "axplat-x86-pc?/fp-simd", "axplat-aarch64-qemu-virt?/fp-simd", "axplat-riscv64-qemu-virt?/fp-simd", "axplat-loongarch64-qemu-virt?/fp-simd"]
rtc = ["axplat-x86-pc?/rtc", "axplat-aarch64-qemu-virt?/rtc", "axplat-riscv64-qemu-virt?/rtc", "axplat-loongarch64-qemu-virt?/rtc"]
paging = ["axalloc", "page_table_multiarch"]
tls = ["axcpu/tls"]
uspace = ["paging", "axcpu/uspace"]

# Custom or default platforms
myplat = []
defplat = ["dep:axplat-x86-pc", "dep:axplat-aarch64-qemu-virt", "dep:axplat-riscv64-qemu-virt", "dep:axplat-loongarch64-qemu-virt"]

default = []
ipi = ["irq"]

[dependencies]
axalloc = { workspace = true, optional = true }
axconfig = { workspace = true }
axlog = { workspace = true }

axcpu = { workspace = true }
axio = { workspace = true }
axplat = { workspace = true }
cfg-if = { workspace = true }
heapless = "0.8"
kernel_guard = { workspace = true }
kspin = { workspace = true }
lazyinit = { workspace = true }
linkme = { version = "0.3.33", optional = true }
log = { workspace = true }
memory_addr = { workspace = true }
page_table_multiarch = { workspace = true, optional = true }
percpu = { workspace = true }

[target.'cfg(target_arch = "x86_64")'.dependencies]
axplat-x86-pc = { version = "0.2", optional = true }

[target.'cfg(target_arch = "aarch64")'.dependencies]
aarch64-cpu = "10.0"
axplat-aarch64-qemu-virt = { version = "0.2", optional = true }

[target.'cfg(target_arch = "riscv64")'.dependencies]
axplat-riscv64-qemu-virt = { version = "0.2", optional = true }

[target.'cfg(target_arch = "loongarch64")'.dependencies]
axplat-loongarch64-qemu-virt = { version = "0.2", optional = true }

[build-dependencies]
axconfig = { workspace = true }
