[package]
name = "axfs-ng"
version = "0.1.0"
edition.workspace = true
authors = ["Mivik <mivikq@gmail.com>"]
license.workspace = true
homepage.workspace = true

[features]
default = ["fat"]
fat = ["dep:fatfs"]
ext4 = ["dep:lwext4_rust"]
times = []
std = ["lwext4_rust?/std"]

[dependencies]
axalloc = { workspace = true }
axdriver = { workspace = true, features = ["block"] }
axhal = { workspace = true }
axio = { workspace = true, features = ["alloc"] }
axsync = { workspace = true }

allocator = { workspace = true }
axerrno = { workspace = true }
axfs-ng-vfs = { workspace = true }
bitflags = "2.9.0"
cfg-if = { workspace = true }
chrono = { workspace = true }
intrusive-collections = "0.9.7"
kspin = { workspace = true }
log = { workspace = true }
lru = "0.16.0"
scope-local = { workspace = true }
slab = { version = "0.4.9", default-features = false }
spin = { workspace = true }

[dependencies.lwext4_rust]
path = "../../../crates/lwext4_rust"
default-features = false
optional = true

[dependencies.fatfs]
git = "https://github.com/Starry-OS/rust-fatfs.git"
rev = "2685439"
default-features = false
optional = true
features = ["alloc", "lfn", "log_level_trace", "unicode"]

[dev-dependencies]
axdriver = { workspace = true, features = ["block", "ramdisk"] }
env_logger = "0.11.8"
